apiVersion: v1
kind: Namespace
metadata:
  name: memallocdemo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memallocdemo-deployment-1
  namespace: memallocdemo
  labels:
    app: memallocdemo-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memallocdemo-1
  template:
    metadata:
      labels:
        app: memallocdemo-1
    spec:
      containers:
      - name: memallocdemo
        image: registry.gitlab.com/cromulentbanana/myreg:latest
        env:
        - name: ALLOCATE_MB
          value: "10000"
        - name: HOLD_ALLOC_TIME
          value: "10s"
        - name: HOLD_FREE_TIME
          value: "10s"
        - name: BIND_ADDRESS
          value: 0.0.0.0
        - name: BUFFER_SIZE
          value: "24"
        - name: LOG_LEVEL
          value: debug
        ports:
        - containerPort: 8484
          name: api
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        resources:
          limits:
            memory: 10Gi
          requests:
            cpu: 1
            memory: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memallocdemo-deployment-2
  namespace: memallocdemo
  labels:
    app: memallocdemo-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memallocdemo-2
  template:
    metadata:
      labels:
        app: memallocdemo-2
    spec:
      containers:
      - name: memallocdemo
        image: registry.gitlab.com/cromulentbanana/myreg:latest
        env:
        - name: ALLOCATE_MB
          value: "10000"
        - name: HOLD_ALLOC_TIME
          value: "10s"
        - name: HOLD_FREE_TIME
          value: "10s"
        - name: BIND_ADDRESS
          value: 0.0.0.0
        - name: BUFFER_SIZE
          value: "24"
        - name: LOG_LEVEL
          value: debug
        ports:
        - containerPort: 8484
          name: api
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        resources:
          requests:
            cpu: 1
            memory: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: memallocdemo-1
  namespace: memallocdemo
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: api
    port: 80
    protocol: TCP
    targetPort: 8484
  selector:
    app: memallocdemo-1
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: memallocdemo-2
  namespace: memallocdemo
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: api
    port: 80
    protocol: TCP
    targetPort: 8484
  selector:
    app: memallocdemo-2
  type: ClusterIP
